language: r
cache: packages
pandoc: false
latex: false

matrix:
  include:
    - os: linux
      dist: xenial
      env: R_CODECOV=true
      sudo: required
    - os: osx
      osx_image: xcode8.3
      brew_packages: coin-or-tools/coinor/cbc
      env:
        - PKG_CONFIG="/usr/local/bin/pkg-config"
        - PKG_CONFIG_PATH="/usr/local/lib/pkgconfig/"

addons:
  apt:
    packages:
      - coinor-libcbc-dev
      - coinor-libclp-dev

r_github_packages:
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
